# Generated by Django 4.0 on 2022-12-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_user_room_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
